  cursor.execute("DROP TABLE  IF EXISTS  patient;")
    cursor.execute("DROP TABLE  IF EXISTS  medical_staff;")
    cursor.execute("DROP TABLE  IF EXISTS  clinic;")
    cursor.execute("DROP TABLE  IF EXISTS  p_history;")
    cursor.execute("DROP TABLE  IF EXISTS  medicine;")